name: "multi event pipeline / workflow"

on:
    push:
        branches:
           - master
           - test
    pull_request:
        branches:
            -master

jobs:
    on-push:  #job1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "running on master push"
              run: echo "running on master push"

    on-pull-request: #job2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request"
              run: echo "running on pull request"
